### ISSUE TITLE
你好，请问fm怎么导入

### ISSUE THREAD

**Issue by Dowson0** [HIM-AIM/RNADiffFold#2]
当我想使用python prediction/predict.py预测我的rna fasta文件的二级结构，却出现了下面问题。

(dgbert) gui@81740c6a6d48:~/960822/zion/RNADiffFold-master/prediction$ python prediction.py
Traceback (most recent call last):
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/prediction.py", line 5, in <module>
    from prediction_utils import *
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/prediction_utils.py", line 14, in <module>
    from models.model import DiffusionRNA2dPrediction
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/models/model.py", line 11, in <module>
    from models.condition.fm_conditioner.pretrained import load_model_and_alphabet_local
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/models/condition/fm_conditioner/pretrained.py", line 6, in <module>
    from models.condition.fm_conditioner import fm
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/models/condition/fm_conditioner/fm/__init__.py", line 10, in <module>
    from . import pretrained  # noqa
  File "/public/home/gui/960822/zion/RNADiffFold-master/prediction/models/condition/fm_conditioner/fm/pretrained.py", line 5, in <module>
    import fm
ModuleNotFoundError: No module named 'fm'

您能给出详细的操作过程吗。感谢

**Comment by festla** [comment]
你好，我想知道这个模型需要的显存最少是多少呢；论文使用的 A40 有 48G ，我想知道 24G 的3090 能跑的起来吗
